//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21448567_HW06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand
    {
        public brand()
        {
            this.products = new HashSet<product>();
        }
    
        public int brand_id { get; set; }
        public string brand_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
